[build]
  publish = "."
  command = "node build-cache-bust.js && echo 'Cache updated - Build complete'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://maps.googleapis.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; img-src 'self' data: https: blob:; font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com; connect-src 'self' https://www.google-analytics.com https://maps.googleapis.com; frame-src 'self' https://www.google.com https://maps.google.com; object-src 'none'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests;"
    # XSS Protection
    X-XSS-Protection = "1; mode=block"
    # Clickjacking Protection
    X-Frame-Options = "DENY"
    # MIME Type Sniffing Protection
    X-Content-Type-Options = "nosniff"
    # Referrer Policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Permissions Policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=(), ambient-light-sensor=(), autoplay=(), fullscreen=(self), picture-in-picture=()"
    # HSTS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # DNS Prefetch Control
    X-DNS-Prefetch-Control = "on"
    # Download Options
    X-Download-Options = "noopen"
    # Cross-Domain Policies
    X-Permitted-Cross-Domain-Policies = "none"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200